name: Deploy to Vercel

on:
 push:
   branches: [development, prod]

jobs:
 deploy:
   runs-on: ubuntu-latest
   if: contains(github.ref, 'refs/heads/prod')
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: "1.22.7" # Specify the Go version to use

     - name: Install dependencies
       run: go mod tidy

     - name: Build project
       run: go build -o server ./api/index.go #ref vercel docs

     - name: Setup Environment variables (main)
       run: |
         echo "GO_ENV=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV

     - name: Setup Environment variables (Prod)
       if: ${{ github.ref == 'refs/heads/prod' }}
       run: |
         echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_PROD }}" >> $GITHUB_ENV
         echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID_PROD }}" >> $GITHUB_ENV

     - name: Deploy to Vercel (Prod)
       if: ${{ github.ref == 'refs/heads/prod' }}
       uses: amondnet/vercel-action@v20
       with:
         vercel-token: ${{ secrets.VERCEL_TOKEN }}
         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_PROD }}
         vercel-org-id: ${{ secrets.VERCEL_ORG_ID_PROD }}
         vercel-args: "--prod"
       env:
         VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

